apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ .Values.nodePoolName }}
spec:
  template:
    spec:
      requirements:
        {{- range .Values.nodepool_requirements }}
        - name: "{{ .key }}"
          operator: {{ .operator }}
          values: 
          {{- range .values }}
            - {{ . | quote }}
          {{- end }}
        {{- end }}
      nodeClassRef:
        name: {{ .Values.nodeClassName }}
  limits:
    cpu: {{ .Values.limits.cpu }}
    memory: {{ .Values.limits.memory }}
  disruption:
    consolidationPolicy: {{ .Values.disruption.consolidationPolicy }}
    consolidationPolicy: {{ .Values.disruption.consolidateAfter }}
    expireAfter: {{ .Values.disruption.expireAfter }}