apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ .Values.nodeClassName }}
spec:
  amiFamily: AL2 
  role: "{{ .Values.eksNodeGroupIAMRole }}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{ .Values.discoveryTag }}"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{ .Values.discoveryTag }}"