nodePoolName: default
nodeClassName: default

eksNodeGroupIAMRole: ""
discoveryTag: ""

cpuLimits: 1000
memoryLimitsGi: 20
expireAfterH: 1

nodepool_requirements:
- key: kubernetes.io/arch
  operator: In
  values: ["amd64"]
- key: kubernetes.io/os
  operator: In
  values: ["linux"]
- key: karpenter.sh/capacity-type
  operator: In
  values: ["spot"]
- key: karpenter.k8s.aws/instance-category
  operator: In
  values: ["c", "m"]
- key: karpenter.k8s.aws/instance-generation
  operator: Gt
  values: ["2"]
